[package]
name = "rusty-1brc"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
memmap2 = "0.9.4"
bstr = "1.9.1"
byteorder = "1.5.0"
fast-float = "0.2.0"
lazy_static = "1.5.0"
rustc-hash = "2.0.0"


[profile.release]
lto = "fat"
codegen-units = 1
